version: 3.24.0.{build}
image: Visual Studio 2017
configuration: Release
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
nuget:
  disable_publish_on_pr: true
build_script:
- ps: dotnet pack -c release src
test_script:
- ps: dotnet test -c release tests -r testResults -l trx
- ps: $wc = New-Object 'System.Net.WebClient'; Get-ChildItem -Recurse *.trx | % { Resolve-Path $_ } | % { $wc.UploadFile("https://ci.appveyor.com/api/testresults/mstest/$($env:APPVEYOR_JOB_ID)", $_) }
artifacts:
- path: '**\*.nupkg'
deploy: off